# H1_etl_config.yml

H_num: H1
H_system: red
start_end: [[2019-11-10, 2019-12-25]]
hubs: [1, 2, 3, 4, 5]
zone_thresholds:
                RS1: 0.3
                RS2: 0.5
                RS3: 0.3
                RS4: 0.3
                RS5: 0.3